seed: 42
model_name: "klue/bert-base"
batch_size: 64
num_labels : 3

train:
    output_dir: "./results"
    save_total_limit: 5
    save_strategy: "epoch"
    logging_dir: "./logs"
    logging_steps: 100
    evaluation_strategy: "epoch"
    load_best_model_at_end: True
    num_train_epochs: 20
    learning_rate: 5e-5
    warmup_steps: 100
    weight_decay: 0.01
    early_stopping_patience: 3
    metric_for_best_model: 'micro f1 score'
    greater_is_better: True

loss:
    loss_type: "ldam"
    gamma: 2.0
    max_m: 0.5
    weight: 1.0
    s: 35

tokenizer:
    return_tensors: "pt"
    padding: "max_length"
    truncation: True
    max_length: 256
    add_special_tokens: True
    entity_marker_type : "kor_typed_entity_marker_punct"

inference:
    model_dir: "/best_model"
    output_dir: "./prediction"
    output_file: "submission.csv"
    val_inference_file : "val_inference.csv"

path:
    train_path: "../dataset/train.csv"
    val_path: "../dataset/dev.csv"
    test_path: "../dataset/test_data.csv"
    split_data_dir: "split_data"
    split_nopreprocess_train_path: "split_data/split_nopreprocess_train.csv"
    split_nopreprocess_val_path: "split_data/split_nopreprocess_val.csv"
    split_preprocess_train_path: "split_data/split_preprocess_train.csv"
    split_preprocess_val_path: "split_data/split_preprocess_val.csv"
  
