seed: 42
model_name: "klue/bert-base"
batch_size: 64

train:
    output_dir: "./results"
    save_total_limit: 5
    save_strategy: "epoch"
    logging_dir: "./logs"
    logging_steps: 100
    evaluation_strategy: "epoch"
    load_best_model_at_end: True
    num_train_epochs: 5
    learning_rate: 5e-5
    warmup_steps: 100
    weight_decay: 0.01
    early_stopping_patience: 3

loss:
    loss_type: "focal"
    alpha: 1.0
    gamma: 2.0

tokenizer:
    return_tensors: "pt"
    padding: True
    truncation: True
    max_length: 256
    add_special_tokens: True

inference:
  model_dir: "./best_model"
  output_dir: "./prediction"
  output_file: "submission.csv"

path:
  train_path: "../dataset/train.csv"
  val_path: "../dataset/dev.csv"
  test_path: "../dataset/test_data.csv"
  split_data_dir: "../dataset/split_data/"
  split_nopreprocess_train_path: "../dataset/split_data/split_nopreprocess_train.csv"
  split_nopreprocess_val_path: "../dataset/split_data/split_nopreprocess_val.csv"
  split_preprocess_train_path: "../dataset/split_data/split_preprocess_train.csv"
  split_preprocess_val_path: "../dataset/split_data/split_preprocess_val.csv"
  